version: '3'
services:
  app: # go app
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - db
  db: # database
    image: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
