version: '3'
services:
  app: # go app
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://myuser:mypassword@db:5432/mydatabase
      SECRET_KEY: "asd12edasd"

  db: # database
    image: postgres:alpine
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase